export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const SET_POSTS = "SET_POSTS";
export const SET_COMMENTS = "SET_COMMENTS";
export const ADD_NEW_POST = "ADD_NEW_POST";
export const REPLACE_ONE_POST = "REPLACE_ONE_POST";
export const REMOVE_ONE_POST = "REMOVE_ONE_POST";

export const SET_LOGOS = "SET_LOGOS";
export const ADD_LOGO = "ADD_LOGO";
export const REMOVE_LOGO = "REMOVE_LOGO";
export const REPLACE_LOGO = "REPLACE_LOGO";

export const SET_SITE_TITLES = "SET_SITE_TITLES";
export const ADD_SITE_TITLE = "ADD_SITE_TITLE";
export const REMOVE_SITE_TITLE = "REMOVE_SITE_TITLE";
export const REPLACE_SITE_TITLE = "REPLACE_SITE_TITLE";

export const SET_FOOTER_CONTENTS = "SET_FOOTER_CONTENTS";
export const ADD_FOOTER_CONTENT = "ADD_FOOTER_CONTENT";
export const REMOVE_FOOTER_CONTENT = "REMOVE_FOOTER_CONTENT";
export const REPLACE_FOOTER_CONTENT = "REPLACE_FOOTER_CONTENT";

export const SET_POST_CATEGORIES = "SET_POST_CATEGORIES";
export const ADD_POST_CATEGORY = "ADD_POST_CATEGORY";
export const REMOVE_POST_CATEGORY = "REMOVE_POST_CATEGORY";
export const REPLACE_POST_CATEGORY = "REPLACE_POST_CATEGORY";